### ISSUE TITLE
Admin (Product page) : Thumbnails are not displaying when added in back end

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Electro-Heat-Engineering#20]
![30](https://cloud.githubusercontent.com/assets/13309806/13524954/36219d22-e224-11e5-950a-0d3270d00d5f.png)

**Comment by roseliesromeo** [comment]
It should display 3 image thumbnails and should be aligned.
![image](https://cloud.githubusercontent.com/assets/11186313/13870928/2df5781a-ed1b-11e5-8fb3-9da279edc8cc.png)
